import CollProvider from "@/components/CollProvider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const inter = Poppins({  weight: "400" ,subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <CollProvider>
            {children}
        </CollProvider>
      </body>
    </html>
  );
}
